name: Watcher
on:
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:

env:
  WATCHER_SCRIPT: watcher.py
  BUILDER_CONFIG_FILE: image-builder.json

jobs:
  images-to-update:
    runs-on: ubuntu-latest
    name: Get images to update
    permissions:
      contents: read
    outputs:
      image-list: ${{ steps.get-images.outputs.images }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get all images
        id: get-images
        run: |
          pip install PyGithub
          IMAGES=$(python $WATCHER_SCRIPT | tr -d '[:space:]')
          echo $IMAGES
          echo "images=$IMAGES" >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v2
        with:
          name: image-builder.json
          path: $BUILDER_CONFIG_FILE

  open-pr:
    runs-on: ubuntu-latest
    needs: images-to-update
    strategy:
      fail-fast: false
      matrix:
        images: ${{ fromJson(needs.images-to-update.outputs.image-list) }}
    name: Pull request for ${{ matrix.images.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/download-artifact@v2
        with:
          name: image-builder.json
          path: $BUILDER_CONFIG_FILE
      - name: Commit file into new branches
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'gha@pokt.network'
          git checkout -b "bump-${{ matrix.images.context }}-to-${{ matrix.images.tag }}"
          sed -i 's/RELEASE="${{ matrix.images.old_tag }}"/RELEASE="${{ matrix.images.tag }}"/g' ${{ matrix.images.context }}/${{ matrix.images.dockerfile }}
          git add .
          git commit -m "Bump ${{ matrix.images.context }} to ${{ matrix.images.tag }}"
          git push --set-upstream origin bump-${{ matrix.images.context }}-to-${{ matrix.images.tag }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Bump ${{ matrix.images.context }} to ${{ matrix.images.tag }}'
          body: This PR is auto-generated.
          base: master
          branch: bump-${{ matrix.images.context }}-to-${{ matrix.images.tag }}
          team-reviewers: pokt-foundation/devops
          delete-branch: true
